name: Continuos Integration

on:
  pull_request:
    paths:
      - app/**

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    env:
      APP_PATH: app
      TESTS_PATH: app/test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt

      - name: Run pytest
        working-directory: ${{ env.TESTS_PATH }}
        run: |
          python -m pytest -v

      - name: Build coverage file
        run: |
          pytest --cache-clear --cov=${{ env.APP_PATH }} ${{ env.TESTS_PATH }} > pytest-coverage.txt

      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
